# Generated by Django 4.2.2 on 2024-02-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicechargerequests_branch_sparerequests_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expensecategory', to='core.branch'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expensetype', to='core.branch'),
        ),
    ]
