# Generated by Django 4.2.2 on 2024-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rack_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField()),
            ],
        ),
    ]
