# Generated by Django 4.2.2 on 2024-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicetax'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='servicetax',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
