# Generated by Django 4.2.2 on 2024-02-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_service_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.branch'),
        ),
    ]
