# Generated by Django 4.2.2 on 2024-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
