# Generated by Django 3.2.20 on 2024-03-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_country_phone_number_digit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentdate', models.DateField(blank=True, default=None, max_length=200, null=True)),
                ('creditaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('debitaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('narration', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='core.branch')),
            ],
        ),
    ]
