# Generated by Django 3.2.20 on 2024-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coasubaccounts_gstring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payments',
        ),
    ]
