# Generated by Django 3.2.20 on 2024-03-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_payment_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='referenceno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
