# Generated by Django 4.2.2 on 2024-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_payments_referenceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpurchase',
            name='purchase_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branchpurchase',
            name='discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
