# Generated by Django 4.2.8 on 2024-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_branch_phone_alter_company_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueidgenerator',
            name='uniqueid',
            field=models.IntegerField(),
        ),
    ]
