# Generated by Django 4.2.8 on 2024-04-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_uniqueidgenerator_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueidgenerator',
            name='uniqueid',
            field=models.BigIntegerField(),
        ),
    ]
