# Generated by Django 4.2.8 on 2024-04-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_uniqueidgenerator_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pattern',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
