# Generated by Django 4.2.2 on 2024-04-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_serviceproduct_phonebrand_product_phonemodal_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebrand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='phonebrand',
            unique_together={('product', 'name')},
        ),
    ]
