# Generated by Django 4.2.2 on 2024-04-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_phonebrand_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicecharge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicecharge', to='core.serviceproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecharge',
            unique_together={('product', 'brand', 'modal', 'issue')},
        ),
    ]
