# Generated by Django 4.2.2 on 2024-04-12 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_alter_servicecharge_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbookingrepair',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerbookingrepair',
            name='product',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
