# Generated by Django 4.2.2 on 2024-04-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_customerbookingrepair_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbookingrepair',
            name='bookingid',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
