# Generated by Django 4.2.2 on 2024-04-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_customerbookingrepair_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='core.customerbookingrepair'),
        ),
    ]
