# Generated by Django 4.2.2 on 2024-05-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='screen_password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
