# Generated by Django 3.2.20 on 2024-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sale_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_head', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('account_type', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
    ]
