# Generated by Django 4.2.2 on 2024-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_singleledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_copy',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
