# Generated by Django 4.2.2 on 2024-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_purchase_invoice_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpurchase',
            name='invoice_copy',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
