# Generated by Django 4.2.2 on 2024-05-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_service_image1_alter_service_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
