# Generated by Django 4.2.8 on 2024-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
