# Generated by Django 4.2.8 on 2024-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_purchase_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchpurchase',
            name='invoicenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
