# Generated by Django 4.2.8 on 2024-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_productpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricelist',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
