# Generated by Django 4.2.8 on 2024-06-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_sale_customer_gst_number_service_customer_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
