# Generated by Django 4.2.8 on 2024-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_branch_createddate_alter_livestreamurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='installation_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='installation_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
