# Generated by Django 4.2.2 on 2024-06-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_installationtax_sale_installation_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SidebarStatus',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_status',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
