# Generated by Django 4.2.8 on 2024-07-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_customerbookingrepair_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_number', models.CharField(max_length=100)),
                ('adjustment', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment', to='core.products')),
            ],
        ),
    ]
