# Generated by Django 4.2.8 on 2024-07-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
    ]
