# Generated by Django 4.2.8 on 2024-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_stockadjustment_purchase_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
