# Generated by Django 3.2.20 on 2024-07-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_country_currency_country_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalid', models.CharField(blank=True, max_length=200, null=True)),
                ('referenceno', models.CharField(blank=True, max_length=200, null=True)),
                ('journaldate', models.DateField(blank=True, default=None, max_length=200, null=True)),
                ('creditaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('debitaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('narration', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('mode', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='core.branch')),
            ],
        ),
    ]
