# Generated by Django 4.2.8 on 2024-07-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebrand',
            name='arabic_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phonemodal',
            name='arabic_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='arabic_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
