# Generated by Django 4.2.2 on 2024-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
