# Generated by Django 4.2.2 on 2024-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_coasubaccounts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceissues',
            name='arabic_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
