# Generated by Django 4.2.2 on 2024-08-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_pagesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesize',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
