# Generated by Django 4.2.8 on 2024-08-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_pagesize_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbookingrepair',
            name='issue',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
