# Generated by Django 4.2.8 on 2024-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_customerbookingrepair_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebrand',
            name='arabic_name',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phonemodal',
            name='arabic_name',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceissues',
            name='arabic_name',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='arabic_name',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
