# Generated by Django 4.2.2 on 2024-08-08 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_phonebrand_arabic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
