# Generated by Django 4.2.2 on 2024-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_customers_customertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='customertype',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
