# Generated by Django 4.2.2 on 2024-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_service_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicerefnumber',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
