# Generated by Django 4.2.2 on 2024-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_service_servicerefnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoicenumber',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
