# Generated by Django 4.2.2 on 2024-08-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_sale_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='invoicenumber',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
