# Generated by Django 4.2.2 on 2024-08-22 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_service_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='invoicedate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
