# Generated by Django 4.2.2 on 2024-08-22 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_sale_invoicedate_alter_service_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoicedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='invoicedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
