# Generated by Django 4.2.2 on 2024-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_sale_invoicedate_alter_service_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoicenumber',
            field=models.CharField(max_length=200),
        ),
    ]
