# Generated by Django 4.2.2 on 2024-08-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_sale_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoicedate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
