# Generated by Django 4.2.8 on 2024-09-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_stocktransaction_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discountmethod',
            field=models.CharField(blank=True, default='Flat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discountpercentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
