# Generated by Django 4.2.8 on 2024-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_service_discountmethod_service_discountpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='purchase_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='purchase_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sparerequests',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sparerequests',
            name='purchase_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
