# Generated by Django 4.2.2 on 2024-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_sale_purchase_price_sale_purchase_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='series',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
