# Generated by Django 4.2.2 on 2024-11-08 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_service_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
