# Generated by Django 4.2.8 on 2024-10-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_service_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDiscountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicerefnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('sparetotal_excltax_afterdiscount', models.FloatField(blank=True, default=0, null=True)),
                ('sparetaxtotal_afterdiscount', models.FloatField(blank=True, default=0, null=True)),
                ('sparetotal_excltax_beforediscount', models.FloatField(blank=True, default=0, null=True)),
                ('sparetaxtotal_beforediscount', models.FloatField(blank=True, default=0, null=True)),
                ('servivcecost_excltax_afterdiscount', models.FloatField(blank=True, default=0, null=True)),
                ('servicetaxtotal_afterdiscount', models.FloatField(blank=True, default=0, null=True)),
                ('servivcecost_excltax_beforediscount', models.FloatField(blank=True, default=0, null=True)),
                ('servicetaxtotal_beforediscount', models.FloatField(blank=True, default=0, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
