# Generated by Django 4.2.2 on 2024-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_cashbook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactiondate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
