# Generated by Django 4.2.10 on 2024-11-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_cashbook_date'),
        ('core', '0088_transaction_transactiondate'),
    ]

    operations = [
    ]
