# Generated by Django 4.2.10 on 2024-12-13 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_merge_20241128_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sidebar_status',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
