# Generated by Django 4.2.10 on 2024-12-13 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_stocktransaction_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechat',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
