# Generated by Django 4.2.10 on 2024-12-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_servicechat_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='purchaseid',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='saleid',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
