# Generated by Django 4.2.10 on 2024-12-14 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_purchasereturn_purchaseid_salereturn_saleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='coasubaccounts',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountgroup')),
            ],
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='account_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounthead'),
        ),
        migrations.AlterField(
            model_name='coasubaccounts',
            name='head_root',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountledger'),
        ),
    ]
