# Generated by Django 4.2.10 on 2024-12-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_accountgroup_accounthead_coasubaccounts_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='creditaccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditaccount_journal', to='core.coasubaccounts'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='debitaccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debitaccount_journal', to='core.coasubaccounts'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='creditaccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditaccount_payment', to='core.coasubaccounts'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='debitaccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debitaccount_payment', to='core.coasubaccounts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='creditaccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditaccount_receipt', to='core.coasubaccounts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='debitaccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debitaccount_receipt', to='core.coasubaccounts'),
        ),
    ]
