# Generated by Django 4.2.10 on 2024-12-19 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_payments_creditaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(max_length=200)),
                ('voucher_id', models.CharField(max_length=200)),
                ('voucher_type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_type', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_ledger', to='core.branch')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountledger')),
                ('subledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coasubaccounts')),
            ],
        ),
    ]
