# Generated by Django 4.2.10 on 2024-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_generalledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='coasubaccounts',
            name='is_adminonly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
