# Generated by Django 4.2.10 on 2024-12-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_coasubaccounts_is_adminonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpurchase',
            name='supplier_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_leger', to='core.coasubaccounts'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_leger', to='core.coasubaccounts'),
        ),
    ]
