# Generated by Django 4.2.10 on 2024-12-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_branchpurchase_supplier_ledger_sale_customer_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_customer', to='core.coasubaccounts'),
        ),
        migrations.AddField(
            model_name='service',
            name='customer_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_leger_service', to='core.coasubaccounts'),
        ),
    ]
