# Generated by Django 4.2.10 on 2024-12-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_customers_customer_ledger_service_customer_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='supplier_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_ledger_supplier', to='core.coasubaccounts'),
        ),
    ]
