# Generated by Django 4.2.10 on 2024-12-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_cashbook_branch_wid_cashbook_subledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='is_opening_stock',
            field=models.BooleanField(default=False),
        ),
    ]
