# Generated by Django 4.2.10 on 2024-12-30 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_stocktransaction_is_opening_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStockValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_value', to='core.branch')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_value', to='core.coasubaccounts')),
            ],
        ),
    ]
