# Generated by Django 4.2.10 on 2025-01-09 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_openingstockvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchpurchase',
            name='barcodenumber',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_customer', to='core.coasubaccounts'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='barcodenumber',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_ledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ledger_supplier', to='core.coasubaccounts'),
        ),
        migrations.CreateModel(
            name='ContraEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraid', models.CharField(blank=True, max_length=200, null=True)),
                ('contradate', models.DateField(blank=True, default=None, max_length=200, null=True)),
                ('narration', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('creditmode', models.CharField(blank=True, max_length=200, null=True)),
                ('debitmode', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra', to='core.branch')),
                ('creditaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditaccount_contra', to='core.coasubaccounts')),
                ('debitaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitaccount_contra', to='core.coasubaccounts')),
            ],
        ),
    ]
