from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(UserProfile)
admin.site.register(Customers)
admin.site.register(UniqueIdGenerator)
admin.site.register(Purchase)
admin.site.register(PurchaseList)
admin.site.register(Suppliers)
admin.site.register(Company)
admin.site.register(Transaction)
admin.site.register(Sale)
admin.site.register(Branch)
admin.site.register(Brand)
admin.site.register(Expenses)
admin.site.register(Stock)
admin.site.register(Service)
admin.site.register(SpareParts)
admin.site.register(BranchStock)
admin.site.register(Products)
admin.site.register(ExpenseCategory)
admin.site.register(ExpenseType)
admin.site.register(Rack)
admin.site.register(ScheduleCallNotifications)
admin.site.register(ServiceCallLogs)
admin.site.register(StockTransferList)
admin.site.register(BranchPurchase)
admin.site.register(Catagories)
admin.site.register(Packing)
admin.site.register(SubCatagories)
admin.site.register(Tax)
admin.site.register(Type)
admin.site.register(PurchaseReturn)
admin.site.register(SaleReturn)
admin.site.register(SpareRequests)
admin.site.register(ServiceHistory)
admin.site.register(BroadcastNotification)
admin.site.register(CustomerBookingRepair)
admin.site.register(Country)
admin.site.register(City)
admin.site.register(ServiceIssues)
admin.site.register(PhoneBrand)
admin.site.register(PhoneModal)
admin.site.register(ServiceCharge)
admin.site.register(ServiceTax)
admin.site.register(PaymentMode)
admin.site.register(StockTransaction)
admin.site.register(ServiceProduct)
admin.site.register(PageSize)
admin.site.register(WhatsappStatus)
admin.site.register(Ledger)
admin.site.register(CashBook)
admin.site.register(CoASubAccounts)
admin.site.register(SingleLedger)
admin.site.register(Payments)
admin.site.register(Receipts)
