# Generated by Django 4.2.2 on 2024-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesocial',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
