# Generated by Django 4.2.2 on 2024-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofilesocial_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesocial',
            name='cover_picture',
            field=models.URLField(default='https://images2.imgbox.com/7f/dd/zU4bMETS_o.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofilesocial',
            name='profile_picture',
            field=models.URLField(default='https://images2.imgbox.com/db/dc/nLkyji55_o.jpeg', max_length=500),
        ),
    ]
