# Generated by Django 4.2.2 on 2024-02-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_userprofilesocial_cover_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotificationsocial',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
