# Generated by Django 4.2.8 on 2024-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_broadcastnotificationsocial_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilesocial',
            name='contributions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilesocial',
            name='verified_contributions',
            field=models.IntegerField(default=0),
        ),
    ]
