# Generated by Django 4.2.8 on 2024-05-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_comment_verified_userprofilesocial_contributions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='company',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
